# Generated by Django 4.2 on 2023-05-16 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('en_title', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='article/%y /%m /%d')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft'), ('t', 'trash')], default='d', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('en_title', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.TimeField()),
                ('sound', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='podcast/%y /%m /%d')),
                ('data_collector', models.CharField(max_length=20)),
                ('text_editor', models.CharField(max_length=20)),
                ('sound_editor', models.CharField(max_length=20)),
                ('graphic_designer', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft'), ('t', 'trash')], default='d', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_podcast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('en_title', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='event/%y /%m /%d')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('expire_time', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('max_user', models.IntegerField()),
                ('users', models.ManyToManyField(related_name='user_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='post.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('en_name', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='category/%y /%m /%d')),
                ('is_sub', models.BooleanField()),
                ('in_menu', models.BooleanField(default=False)),
                ('parent', models.ManyToManyField(blank=True, to='post.category')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_article', to='post.category'),
        ),
    ]
