# Generated by Django 4.2 on 2023-05-16 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_article_image_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='data_collector',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='graphic_designer',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='sound_editor',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='text_editor',
        ),
    ]
