# Generated by Django 4.2 on 2023-05-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_podcast_data_collector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='speaker',
        ),
    ]
