# Generated by Django 4.2 on 2023-05-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_comment_article_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_article', to='post.comment'),
        ),
    ]
