# Generated by Django 4.2 on 2023-05-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_article_comment_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment_article', to='post.comment'),
        ),
    ]
