# Generated by Django 4.2 on 2023-05-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_article_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment_podcast', to='post.comment'),
        ),
    ]
