# Generated by Django 4.2 on 2023-05-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_podcast_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('w', 'waiting')], default='w', max_length=1),
        ),
    ]
