# Generated by Django 4.2 on 2023-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_comment_user_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_type',
            field=models.CharField(choices=[('a', 'article'), ('p', 'podcast')], max_length=1, null=True),
        ),
    ]
