# Generated by Django 4.2 on 2023-05-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/article/%y /%m /%d'),
        ),
    ]
