# Generated by Django 4.2 on 2023-05-22 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0018_podcast_data_collector_podcast_graphic_designer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
