# Generated by Django 4.2 on 2023-05-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_remove_comment_body_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
