# Generated by Django 4.2 on 2023-05-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/user_upload/%y /%m /%d'),
        ),
    ]
