# Generated by Django 4.2 on 2023-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='data_collector',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='graphic_designer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='sound_editor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='speaker',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='text_editor',
            field=models.CharField(max_length=30),
        ),
    ]
