# Generated by Django 4.2 on 2023-06-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_alter_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/Journal/%y /%m /%d')),
                ('title', models.CharField(max_length=30)),
                ('src', models.URLField()),
            ],
        ),
    ]
