# Generated by Django 4.2 on 2023-06-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='src',
            field=models.FileField(upload_to='file/Journal/%y /%m /%d'),
        ),
    ]
