# Generated by Django 4.2 on 2023-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0038_alter_journal_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='en_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
