# Generated by Django 4.2 on 2023-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0040_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(),
        ),
    ]
