# Generated by Django 4.2 on 2023-05-16 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
