# Generated by Django 4.2 on 2023-05-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='teacher',
            name='en_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='en_title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='en_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
