# Generated by Django 4.2 on 2023-05-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_category_teacher_en_name_teacher_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio_link',
            field=models.URLField(),
        ),
    ]
