# Generated by Django 4.2 on 2023-05-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_teacher_bio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='en_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
