# Generated by Django 4.2 on 2023-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_teacher_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.TimeField(verbose_name='course/image/%y /%m /%d'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video_file',
            field=models.FileField(upload_to='course/video/%y /%m /%d'),
        ),
    ]
