# Generated by Django 4.2 on 2023-06-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_created_at_alter_course_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('en_name', models.CharField(max_length=20, unique=True)),
                ('slug', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
