# Generated by Django 4.2 on 2023-06-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_coursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='course.coursecategory'),
            preserve_default=False,
        ),
    ]
