# Generated by Django 4.2 on 2023-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_coursevideo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='teacher',
            field=models.CharField(default='rasouli', max_length=40),
            preserve_default=False,
        ),
    ]
