# Generated by Django 4.2 on 2023-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_coursevideo_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='en_title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='en_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
