# Generated by Django 4.2 on 2023-05-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
