# Generated by Django 4.2 on 2023-05-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='image/slider/%y /%m /%d'),
        ),
    ]
